config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :query_tasks
  resource :users
  resources :people
  resources :solutions
  resources :comments
  get "run_solution", to: "solutions#run_solution"
  root "pages#home"

end

app/models/query_task.rb
# == Schema Information
#
# Table name: query_tasks
#
#  id                :integer          not null, primary key
#  name              :string
#  description       :text
#  user_id           :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  resource          :string
#  singularize       :boolean          default(FALSE)
#  solution_template :text
#

class QueryTask < ActiveRecord::Base

  validates_presence_of :name, :description

  belongs_to :user
  has_many :solutions
  has_many :comments

  def solved_by(user)
    solutions.map(&:user_id).include?(user.id) ? true : false
  end

end

app/controllers/query_tasks_controller.rb
class QueryTasksController < ApplicationController
  before_action :set_query_task, only: [:show, :edit, :update, :destroy]
  before_action :get_list_of_models, only: [:new, :edit]

  def index
    @query_tasks = QueryTask.includes(solutions: :user).all
  end

  def show
  end

  def new
    @query_task = current_user.query_tasks.new
  end

  def edit
  end

  def create
    @query_task = current_user.query_tasks.new(query_task_params)

    respond_to do |format|
      if @query_task.save
        format.html { redirect_to @query_task, notice: 'Query task was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @query_task.update(query_task_params)
        format.html { redirect_to @query_task, notice: 'Query task was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @query_task.destroy
    respond_to do |format|
      format.html { redirect_to query_tasks_url, notice: 'Query task was successfully destroyed.' }
    end
  end

  private
    def set_query_task
      @query_task = QueryTask.includes(solutions: :user).find(params[:id])
    end

    def query_task_params
      params.require(:query_task).permit(:name, :description, :user_id, :resource, :singularize, :solution_template)
    end

    def get_list_of_models
      @models_singularized = []
      @models_pluralized = []
      @models = (ActiveRecord::Base.connection.tables.map.to_a - ["users", "schema_migrations", "solutions", "query_tasks"])
      @models.each do |model|
        @models_singularized << "<option>"+model.singularize+"</option>"
        @models_pluralized << "<option>"+model+"</option>"
      end
    end

end

app/helpers/query_tasks_helper.rb
module QueryTasksHelper
end

app/views/query_tasks/_form.html.erb
<%= form_for(@query_task) do |f| %>
  <% if @query_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@query_task.errors.count, "error") %> prohibited this query_task from being saved:</h2>

      <ul>
      <% @query_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :singularize %><br>
    <%= f.check_box :singularize, class: "js_singularizer", onchange: "populate_select();" %>
  </div>
  <div class="field">
    <%= f.label :resource %><br>
    <!-- <select name="query_task[resource]" id="query_task_resource"><%#= @models_pluralized.join().html_safe %></select> -->
    <%= f.select :resource, options_for_select(@models, f.object.resource) %>
  </div>
  <div class="field">
    <%= f.label :solution_template %><br>
    <%= f.text_area :solution_template %>
  </div>
  <div class="actions">
    <%= f.submit "Create Task", class: "btn btn-success" %>
  </div>
<% end %>
<script>
function populate_select(){
  var checked = $("#query_task_singularize").is(':checked');
  if(checked){
    $("#query_task_resource").empty().append("<%= @models_singularized.join().html_safe %>");
  }
  else{
    $("#query_task_resource").empty().append("<%= @models_pluralized.join().html_safe %>");
  }
};
</script>

app/views/query_tasks/_query_task.html.erb
<p>
  <strong>Name:</strong>
  <%= @query_task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @query_task.description %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @query_task.resource %>
</p>

<p>
  <strong>Written by:</strong>
  <%= @query_task.user.email %>
</p>

<p>
  <strong>Solution Columns</strong>
  <pre><%= @query_task.solution_template %></pre>
</p>

app/views/query_tasks/edit.html.erb
<h1>Editing Query Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @query_task %> |
<%= link_to 'Back', query_tasks_path %>

app/views/query_tasks/index.html.erb
<%= link_to 'New Query task', new_query_task_path, class: "btn btn-primary" %>

<h1>Listing Query Tasks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Written by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @query_tasks.each do |query_task| %>
      <tr style="<%= query_task.solved_by(current_user) ? 'background-color: rgba(0,255,30,0.1)' : '' %>">
        <td><%= query_task.name %></td>
        <td><%= query_task.description.truncate(50) %></td>
        <td><%= query_task.user.email %></td>
        <td><%= link_to 'Show', query_task, class: "btn btn-default btn-xs" %></td>
        <td><%= link_to 'Edit', edit_query_task_path(query_task), class: "btn btn-warning btn-xs" %></td>
        <td><%= link_to 'Destroy', query_task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/query_tasks/new.html.erb
<h1>New Query Task</h1>

<%= render 'form' %>

<%= link_to 'Back', query_tasks_path %>

app/views/query_tasks/show.html.erb
<%= render @query_task %>
<%= link_to 'Edit', edit_query_task_path(@query_task), class: "btn btn-warning" %>
<%= link_to 'Back', query_tasks_path, class: "btn btn-default" %>
<%= link_to 'Solve', new_solution_path(query_task_id: @query_task.id), class: "btn btn-primary" %>

<h2>Solutions</h2>
<% if @query_task.solutions.any? && !@query_task.solved_by(current_user) %>
  <div class="btn btn-info" onclick="$('.jq_solutions').slideToggle();"">Show solutions</div>
<% end %>
<div class="jq_solutions" style='<%= @query_task.solved_by(current_user) ? "" : "display: none;" %>'>
  <% @query_task.solutions.each do |solution| %>
    <h4><%= solution.user.email %></h4>
    <pre><%= solution.code %></pre>
    <%= link_to "Run", run_solution_path(id: solution.id), class: "btn btn-primary btn-sm", remote: true %>
    <div class="btn btn-default" onclick="$('.solution-<%= solution.id %>').empty();">cls</div>
    <% if solution.user == current_user %>
      <%= link_to "Edit", edit_solution_path(solution), class: "btn btn-warning btn-sm" %>
      <%#= link_to 'Destroy', solution, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
    <% end %>
    <div class="solution-<%= solution.id %>"></div>
  <% end %>
</div>

<h2>Comments</h2>
<div class="jq_comments">
  <% @query_task.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
</div>
  <%= render 'comments/form' %>