config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :query_tasks
  resource :users
  resources :people
  resources :solutions
  resources :comments
  get "run_solution", to: "solutions#run_solution"
  root "pages#home"

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id            :integer          not null, primary key
#  name          :string
#  email         :string
#  profession_id :integer
#  dob           :date
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Person < ActiveRecord::Base

  validates_presence_of :name, :email, :dob, :profession_id

  belongs_to :profession
  has_many :favorite_desserts
  has_many :desserts, through: :favorite_desserts

  def profession_name
    profession.name
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.includes(:profession).all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
    end
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name, :email, :profession_id, :dob)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for @person, class: "form-horizontal" do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :profession_id %><br>
    <%= f.collection_select(:profession_id, Profession.all, :id, :name) %>
  </div>
  <div class="form-group">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit "Create Person", class: "btn btn-success" %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person, class: "btn btn-default" %>
<%= link_to 'Back', people_path, class: "btn btn-default" %>

app/views/people/index.html.erb
<%= link_to 'New person', new_person_path, class: "btn btn-primary" %>

<h1>Listing people</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Dob</th>
      <th>Profession</th>
      <th colspan="36"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= person.dob.strftime("%d.%m.%Y.") %></td>
        <td><%= person.profession_name %></td>
        <td><%= link_to 'Show', person, class: "btn btn-default btn-xs" %></td>
        <td><%= link_to 'Edit', edit_person_path(person), class: "btn btn-warning btn-xs" %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path, class: "btn btn-default" %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @person.profession_id %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @person.dob %>
</p>

<%= link_to 'Edit', edit_person_path(@person), class: "btn btn-warning" %>
<%= link_to 'Back', people_path, class: "btn btn-default" %>